name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Workflows
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'ap-south-1' }}

      - name: Execute Deployment via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=EmployeeHub-EC2" \
            --parameters 'commands=["bash /home/ubuntu/scripts/deploy.sh ${{ inputs.image_tag }}"]'

      - name: Health Check
        run: |
          echo "Waiting for health check..."
          sleep 60
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=EmployeeHub-EC2" \
            --parameters 'commands=["bash /home/ubuntu/scripts/health-check.sh"]'
