name: Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: Workflows
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'ap-south-1' }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate
        working-directory: terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color
        working-directory: terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform
